name: PR Linter

on:
  pull_request:
    types: [opened, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR Title and Branch
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BRANCH="${{ github.head_ref }}"
        
        # Check for CamelCase in the title (must start with a capital letter and contain only letters and numbers)
        if ! [[ "$PR_TITLE" =~ ^[A-Z][a-zA-Z0-9]* ]]; then
          echo "::error::PR title must be in CamelCase. Please update the title."
          exit 1
        fi

        # Check if the title ends with Jira ticket ID (e.g., '(AST-XXXX)')
        if ! [[ "$PR_TITLE" =~ \(AST-[0-9]+\)$ ]]; then
          echo "::error::PR title must contain a Jira ticket ID at the end in the format '(AST-XXXX)'."
          exit 1
        fi

        # Check if branch starts with "bug/" or "feature/"
        if ! [[ "$PR_BRANCH" =~ ^(bug|feature)/ ]]; then
          echo "::error::Branch name must start with 'bug/' or 'feature/'."
          exit 1
        fi

      shell: bash
